class AddCase{
    SelectAnyCase()
    AddCasebutton(){}
    PatientNameInput(){}
    GenderInput(){}
    DateofBirth(){}
    MedicalRecordNumberInput(){}
    InsuranceInput(){}
    DateofSurgery(){}
    MedicalRecordNumberinput(){}
    InstituionInput(){}
    ProcedureTypeInput(){}
    RoleInput(){}
    FindingsInput(){}
    ComplicationsInput(){}
    OutcomeInput(){}
    SelectFollowUp(){}
    SelectDay(){}
    NoteInput(){}
    AddNote(){}
    AddNote2(){}
    AddImage(){}
    AddDiagnosis(){}
    AddDiagnosisSearchInput(){}
    AddDiagnosisSearchButton(){}
    AddDiagnosisCheckBox(){}
    SaveDiagnosis(){}
    CancelDiagnosis(){}
    AddCPT(){}
    AddCPTSearchInput(){}
    AddCPTSearchButton(){}
    AddCPTCheckBox(){}
    SaveAddCPT(){}
    CancelAddCPT(){}
    SaveButton(){}
}
export default AddCase